{% set name = "xattr" %}
{% set version = "0.10.1" %}
{% set bundle = "tar.gz" %}
{% set hash = "c12e7d81ffaa0605b3ac8c22c2994a8e18a9cf1c59287a1b7722a2289c952ec5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
  skip: true  # [win]
  skip: true  # [py<38]
  entry_points:
    - xattr = xattr.tool:main
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cffi 1.15.1
    - setuptools
    - wheel
  run:
    - python
    - cffi >=1.0.0
test:
  requires:
    - pip
  imports:
    - xattr
  commands:
    - xattr --help
    - pip check

about:
  home: https://github.com/xattr/xattr
  license_file: LICENSE.txt
  license: MIT
  license_family: MIT
  summary: Python wrapper for extended filesystem attributes
  description: xattr is a Python wrapper for extended filesystem attributes.
  dev_url: https://github.com/xattr/xattr
  doc_url: https://github.com/xattr/xattr

extra:
  recipe-maintainers:
    - jonashaag
    - pmlandwehr
