# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Y3KksXVog1NqCMcPSyBk1oX0sJSl4dF4RJzdvBYi1zRbyGnYs886uD+t2Y32WO9LAuez3MCaTUE6CbOdr70A3n9HDUgyDsv4LX0hmNiSmePFCLQZOGijEYBwXmzubmiw1mgLAFafLTu3khjBh7oaO8FIwP9/FRaRx0klFYkIzBGotntyoHmpaEKxL91emkrlG7i2mG+joMIAbxxw0DIOSMcAwJHH7wjbQWc1f0/tJ9gtHAvAUM3A4bbE4Xl9mGUT6t3dsyYKFPXJruAjPD24OahRsaDBniSmDujZD/FPkdj201WiiBLmHtRMNCSPS5vn7oU4JKTaXSdmlGbdWFD7rwDn9WOXRGLSvh3C1rL0U6lnIIljHPuPyHufK9mTTBR5HQf825J+Raxoz+3M+Yl5jvmNaPTJ8XiSlMQVWmKe+o+TJQkOijhYiVsarr0VB472AVq3hmtCsoUp7ls0kM/ZTunuDMQ6TSIVhoLK/Jc9ThGiCI06S2TpeKd3Dv3MhQXjlnKq0+gLirbPSuZ/+yVtQzVj3IM/PGMQw3B64aZX4f1FHwhfYmlWLHfaODgFs1y8tyfIg2EakFuXzuzYIx0SdEo5jOErSdvKDhywGNtBavFYAadpoGuzG48xSMSky4Kn18G6zWVMVB2+gv7X6oU5ygcXlfwiiiKKzASHLdbP4kQ="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
