travis:
  secure:
    BINSTAR_TOKEN: Y3KksXVog1NqCMcPSyBk1oX0sJSl4dF4RJzdvBYi1zRbyGnYs886uD+t2Y32WO9LAuez3MCaTUE6CbOdr70A3n9HDUgyDsv4LX0hmNiSmePFCLQZOGijEYBwXmzubmiw1mgLAFafLTu3khjBh7oaO8FIwP9/FRaRx0klFYkIzBGotntyoHmpaEKxL91emkrlG7i2mG+joMIAbxxw0DIOSMcAwJHH7wjbQWc1f0/tJ9gtHAvAUM3A4bbE4Xl9mGUT6t3dsyYKFPXJruAjPD24OahRsaDBniSmDujZD/FPkdj201WiiBLmHtRMNCSPS5vn7oU4JKTaXSdmlGbdWFD7rwDn9WOXRGLSvh3C1rL0U6lnIIljHPuPyHufK9mTTBR5HQf825J+Raxoz+3M+Yl5jvmNaPTJ8XiSlMQVWmKe+o+TJQkOijhYiVsarr0VB472AVq3hmtCsoUp7ls0kM/ZTunuDMQ6TSIVhoLK/Jc9ThGiCI06S2TpeKd3Dv3MhQXjlnKq0+gLirbPSuZ/+yVtQzVj3IM/PGMQw3B64aZX4f1FHwhfYmlWLHfaODgFs1y8tyfIg2EakFuXzuzYIx0SdEo5jOErSdvKDhywGNtBavFYAadpoGuzG48xSMSky4Kn18G6zWVMVB2+gv7X6oU5ygcXlfwiiiKKzASHLdbP4kQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
