travis:
  secure:
    BINSTAR_TOKEN: kwe70kwTJoBPJlPYKWP2++NaSSJ8IRdpOp7GEWq3IBsNy3eOt5KItBjRk03nereq8uw7tKaBBsr8eRVGpsZLDRXU1S+x+mCW/gW9Gn1D8Cf5A8frbLznJKxJCE3djralkEtOYk+hiVnihZTljSrIm2Wu+uoBZUo8bpoQTo2eLBOREJ3x0I8R7YIZE/ZWM1iXC2IeEZw5aOmfW9JPTjVvEEW3vepnuyHny4+4CHdsKKKElf0W/8eYFU8zwDafnkWiwg1CaecIFhcKucxzGncfIYvqzz4gGnLmVg7F6dIbOL+vpZGnIsqkvzb8m1Ohea1ZbXz+dDO/ZaHrVWQk9BxcouCpruRoUj9PlPq5JWKzi4NtLbRTyM3aihRRJS7oHrGGSGxA/8c1OCxty+duQq4hlv/2xwIItTTgDzJIgJtLSORNFjkmKoHbLulXSAJc5l/vBBQ1d84+e72BQIGcgh2eb9JsiHaC/eOguPed7KBCUJPGk6GZ6hUizJIoG0zv7pdl8VKyfG2QGQ39qN33CkijCBZi/U6TzCW3VO4f09tvYOoJYYN5k35CzKUUuomIRCJkDdpWr6I+dLOb2kQs7+tljrc//ssNjqvH4LYi9Bp/A+Dv2JAS7xqTb226RUDznbvB7zGjbte0fvEKbf1zt2aAT3aWB4HcjtWa/JO5bbiECiI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
